apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kr4eqgbye-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kr4eqgbye-go 
  name: kr4eqgbye-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kr4eqgbye-go 
